// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

/********************************************************************************/ /**
 \file      MetaXRAudio_Defaults.h
 \brief     OVR Audio SDK default values - legacy compatibility header
 ************************************************************************************/

#ifndef OVR_Audio_Defaults_h
#define OVR_Audio_Defaults_h

#include "MetaXRAudio_Defaults.h"

// Backwards compatibility defines that map OVRA_ prefixed names to MXRA_ prefixed names
#define OVRA_DEFAULT_VOICE_LIMIT MXRA_DEFAULT_VOICE_LIMIT
#define OVRA_VOICE_LIMIT_MINIMUM MXRA_VOICE_LIMIT_MINIMUM
#define OVRA_VOICE_LIMIT_MAXIMUM MXRA_VOICE_LIMIT_MAXIMUM

#define OVRA_COORDINATE_MAXIMUM MXRA_COORDINATE_MAXIMUM

#define OVRA_UNIT_SCALE_MINIMUM MXRA_UNIT_SCALE_MINIMUM
#define OVRA_UNIT_SCALE_MAXIMUM MXRA_UNIT_SCALE_MAXIMUM
#define OVRA_DEFAULT_UNIT_SCALE MXRA_DEFAULT_UNIT_SCALE

#define OVRA_ATTENUATION_RANGE_MINIMUM MXRA_ATTENUATION_RANGE_MINIMUM
#define OVRA_ATTENUATION_RANGE_MAXIMUM MXRA_ATTENUATION_RANGE_MAXIMUM
#define OVRA_DEFAULT_ATTENUATION_RANGE_MINIMUM MXRA_DEFAULT_ATTENUATION_RANGE_MINIMUM
#define OVRA_DEFAULT_ATTENUATION_RANGE_MAXIMUM MXRA_DEFAULT_ATTENUATION_RANGE_MAXIMUM

#define OVRA_HRTF_INTENSITY_MINIMUM MXRA_HRTF_INTENSITY_MINIMUM
#define OVRA_HRTF_INTENSITY_MAXIMUM MXRA_HRTF_INTENSITY_MAXIMUM
#define OVRA_DEFAULT_HRTF_INTENSITY MXRA_DEFAULT_HRTF_INTENSITY

#define OVRA_SHARED_REFLECTIONS_SEND_GAIN_MINIMUM MXRA_SOURCE_REFLECTIONS_SEND_GAIN_MINIMUM
#define OVRA_SHARED_REFLECTIONS_SEND_GAIN_MAXIMUM MXRA_SOURCE_REFLECTIONS_SEND_GAIN_MAXIMUM
#define OVRA_DEFAULT_SHARED_REFLECTIONS_SEND_GAIN MXRA_DEFAULT_SOURCE_REFLECTIONS_SEND_GAIN

#define OVRA_SHARED_REVERB_SEND_GAIN_MINIMUM MXRA_SOURCE_ACOUSTICS_SEND_GAIN_MINIMUM
#define OVRA_SHARED_REVERB_SEND_GAIN_MAXIMUM MXRA_SOURCE_ACOUSTICS_SEND_GAIN_MAXIMUM
#define OVRA_DEFAULT_SHARED_REVERB_SEND_GAIN MXRA_DEFAULT_SOURCE_ACOUSTICS_SEND_GAIN

#define OVRA_DIRECTIVITY_INTENSITY_MINIMUM MXRA_DIRECTIVITY_INTENSITY_MINIMUM
#define OVRA_DIRECTIVITY_INTENSITY_MAXIMUM MXRA_DIRECTIVITY_INTENSITY_MAXIMUM
#define OVRA_DEFAULT_DIRECTIVITY_INTENSITY MXRA_DEFAULT_DIRECTIVITY_INTENSITY

#define OVRA_OCCLUSION_INTENSITY_MINIMUM MXRA_OCCLUSION_INTENSITY_MINIMUM
#define OVRA_OCCLUSION_INTENSITY_MAXIMUM MXRA_OCCLUSION_INTENSITY_MAXIMUM
#define OVRA_DEFAULT_OCCLUSION_INTENSITY MXRA_DEFAULT_OCCLUSION_INTENSITY

#define OVRA_REVERB_REACH_MINIMUM MXRA_REVERB_REACH_MINIMUM
#define OVRA_REVERB_REACH_MAXIMUM MXRA_REVERB_REACH_MAXIMUM
#define OVRA_DEFAULT_REVERB_REACH MXRA_DEFAULT_REVERB_REACH

#define OVRA_RADIUS_MINIMUM MXRA_VOLUMETRIC_RADIUS_MINIMUM
#define OVRA_RADIUS_MAXIMUM MXRA_VOLUMETRIC_RADIUS_MAXIMUM
#define OVRA_DEFAULT_RADIUS MXRA_DEFAULT_VOLUMETRIC_RADIUS

#define OVRA_ROOM_SIZE_MINIMUM MXRA_SHOEBOX_SIZE_MINIMUM
#define OVRA_ROOM_SIZE_MAXIMUM MXRA_SHOEBOX_SIZE_MAXIMUM
#define OVRA_DEFAULT_ROOM_SIZE_X MXRA_DEFAULT_SHOEBOX_SIZE_X
#define OVRA_DEFAULT_ROOM_SIZE_Y MXRA_DEFAULT_SHOEBOX_SIZE_Y
#define OVRA_DEFAULT_ROOM_SIZE_Z MXRA_DEFAULT_SHOEBOX_SIZE_Z

#define OVRA_ROOM_REFLECT_MINIMUM MXRA_SHOEBOX_REFLECT_MINIMUM
#define OVRA_ROOM_REFLECT_MAXIMUM MXRA_SHOEBOX_REFLECT_MAXIMUM
#define OVRA_DEFAULT_ROOM_REFLECT_LEFT MXRA_DEFAULT_SHOEBOX_REFLECT
#define OVRA_DEFAULT_ROOM_REFLECT_RIGHT MXRA_DEFAULT_SHOEBOX_REFLECT
#define OVRA_DEFAULT_ROOM_REFLECT_UP MXRA_DEFAULT_SHOEBOX_REFLECT
#define OVRA_DEFAULT_ROOM_REFLECT_DOWN MXRA_DEFAULT_SHOEBOX_REFLECT
#define OVRA_DEFAULT_ROOM_REFLECT_BACK MXRA_DEFAULT_SHOEBOX_REFLECT
#define OVRA_DEFAULT_ROOM_REFLECT_FRONT MXRA_DEFAULT_SHOEBOX_REFLECT

#define OVRA_REVERB_WET_MIX_MINIMUM MXRA_SHARED_REVERB_LEVEL_MINIMUM
#define OVRA_REVERB_WET_MIX_MAXIMUM MXRA_SHARED_REVERB_LEVEL_MAXIMUM
#define OVRA_DEFAULT_REVERB_WET_MIX MXRA_DEFAULT_SHARED_REVERB_LEVEL

#define OVRA_CONTROL_ZONE_REVERB_LEVEL_MINIMUM MXRA_CONTROL_ZONE_REVERB_LEVEL_MINIMUM
#define OVRA_CONTROL_ZONE_REVERB_LEVEL_MAXIMUM MXRA_CONTROL_ZONE_REVERB_LEVEL_MAXIMUM
#define OVRA_CONTROL_ZONE_RT60_MINIMUM MXRA_CONTROL_ZONE_RT60_MINIMUM
#define OVRA_CONTROL_ZONE_RT60_MAXIMUM MXRA_CONTROL_ZONE_RT60_MAXIMUM
#define OVRA_CONTROL_ZONE_REFLECTION_TIME_MINIMUM MXRA_CONTROL_ZONE_REFLECTION_TIME_MINIMUM
#define OVRA_CONTROL_ZONE_REFLECTION_TIME_MAXIMUM MXRA_CONTROL_ZONE_REFLECTION_TIME_MAXIMUM

#endif // OVR_Audio_Defaults_h
